kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: ts-board
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: ts-board
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: ts-board
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    api_token: >-
      AgAGOJU2tsbb0psLqwNirvnGaVhDh5JLD5mUOZMHF5e2KWQCBd3Pjd5Hn4CKTa9bWmxXFc6FHz81yXjqHxeqIVnhOWfux/XSyDJy2TovygdYkY6czXLvnqSqJ/oXZy3/uhQXR6NYU5P83WveMPyZQwNITqJE2l99/PlWWUteQLz/oJf/6Gn4Yw6RQ6+2ASLH9G9lrDn5rVnY7tLRRC5aWV8OCGulkOiPPHu4AyLuYNiPVULZccM8pdC3WW4P646KakABLrHqCPCUxV0hCDcnR+e9/uu+ZvvC+CCqPsHzcWTT0yXYJqOPy39mbLEFtyJ1i7PusEtsNPBd3qEH/nnUyEffontzYCO54inm8cc5/TecT+USLdgnqivChPlQETrinRzht5OOCkmJfUkbzDr7ohYkUuTgAlJFK9gzQ92Cq3Ig1C/onS3Tem31Ka94HMCfdZu2VKk/aQ6TdpbPO++ob4cRl6TcOsjrf/78KyhqndKscSTZIkWK/non52yZ9bbz8vS5oY9/G/9PHRhfu919scv2y0vcOMJD8V3+hHeHs8e3Xk1+EK///p3K3zrDhjoOSQHbGwzJtSXhG9uSeG2rA+oWQZeYaFcHnfIxu2Xts7CH/KPjr7axgdNTAKNLFVA82/FmKopoYCxVT+A9kieTM7kuLI5txqApIMIpFDrgdR+DXZlwlqAnFvyYeQWCvak8VUFDziU2vTZqLeNNUcFy+wITN3D/mU9ll4dNt9x0rVBq0BBLPGQV5QONjw6MzumOE/q3U78ySB/W7fNx3l4381NI/IDVXdi8MBYmhg07o69J9DJJiEuMANztcbxBf9gtOICaV5hClETHMTRctgne4vtypwl3NfJS/zJ+92Ot35qfwcMkaRxWk4i/7Op4lCC+93an1Cx2CpTL+8bCXqda3x32x+gvYSwr/HeajVgA+Y4BuqBd1E2ltJj0VrSBkwYuRog=
