gitops-runtime:
  global:
    codefresh:
      accountId: 651bd573a935bf255bb155c2
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: cf
